# Generated by Django 6.0.3 on 2026-04-23 08:34

import banking.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('service', 'Service'), ('ecommerce', 'E-commerce'), ('digital', 'Digital')], max_length=20)),
                ('online', models.BooleanField(default=False)),
                ('sanctioned', models.BooleanField(default=False)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'banking_business',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=banking.models.generate_hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_key', models.SlugField(unique=True)),
                ('account_type', models.CharField(choices=[('current', 'Current'), ('savings', 'Savings'), ('credit', 'Credit')], max_length=20)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed'), ('pending', 'Pending')], default='active', max_length=20)),
                ('account_number', models.CharField(max_length=8, unique=True)),
                ('sort_code', models.CharField(max_length=8)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('round_up_enabled', models.BooleanField(default=False)),
                ('round_up_pot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banking_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(default=banking.models.generate_hex_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('scheme', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'Amex')], max_length=20)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('masked_number', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=5)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('frozen', models.BooleanField(default=False)),
                ('contactless_enabled', models.BooleanField(default=True)),
                ('online_payments_enabled', models.BooleanField(default=True)),
                ('atm_withdrawals_enabled', models.BooleanField(default=True)),
                ('spending_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('spending_limit_period', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='banking.account')),
            ],
            options={
                'db_table': 'banking_card',
                'ordering': ['account', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreditAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('available_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('minimum_payment_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('statement_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_details', to='banking.account')),
            ],
            options={
                'db_table': 'banking_creditaccountdetails',
            },
        ),
        migrations.CreateModel(
            name='SavingsAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('interest_earned_ytd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_details', to='banking.account')),
            ],
            options={
                'db_table': 'banking_savingsaccountdetails',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('card_payment', 'Card Payment'), ('bank_transfer', 'Bank Transfer'), ('direct_debit', 'Direct Debit'), ('standing_order', 'Standing Order'), ('cash_withdrawal', 'Cash Withdrawal'), ('cash_deposit', 'Cash Deposit'), ('interest', 'Interest'), ('fee', 'Fee'), ('refund', 'Refund'), ('round_up_transfer', 'Round-up Transfer'), ('credit_payment', 'Credit Card Payment')], max_length=30)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('declined', 'Declined'), ('reversed', 'Reversed')], default='completed', max_length=20)),
                ('direction', models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('internal', 'Internal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('terminal_id', models.CharField(blank=True, max_length=50)),
                ('payer_name', models.CharField(blank=True, max_length=100)),
                ('payee_name', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('sort_code_masked', models.CharField(blank=True, max_length=8)),
                ('account_number_masked', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.business')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.card')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='banking.account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='banking.account')),
            ],
            options={
                'db_table': 'banking_transaction',
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('joint_owner', 'Joint Owner'), ('viewer', 'Viewer')], default='owner', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_users', to='banking.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'banking_accountuser',
                'ordering': ['account', 'user'],
                'unique_together': {('account', 'user')},
            },
        ),
    ]
