# Generated by Django 6.0.3 on 2026-04-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='network_card_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
