# Generated by Django 6.0.3 on 2026-04-28 19:57

import banking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_card_network_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=banking.models.generate_account_number, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sort_code',
            field=models.CharField(default=banking.models.generate_sort_code, max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='banking.account'),
        ),
    ]
