# Generated by Django 6.0.3 on 2026-04-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_accountuser_lastlogin_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='lastLogin',
        ),
    ]
