# Generated by Django 6.0.3 on 2026-05-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_remove_userprofile_address_userprofile_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_home',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
