# Generated by Django 6.0.3 on 2026-05-04 09:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_userprofile_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='round_up_increment',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
    ]
